name       : nss-mdns
version    : 0.10
release    : 2
source     :
    - http://0pointer.de/lennart/projects/nss-mdns/nss-mdns-0.10.tar.gz : 1e683c2e7c3921814706d62fbbd3e9cbf493a75fa00255e0e715508d8134fa6d
license    : LGPL-2.1
component  : network.util
summary    : glibc plugin for .local name resolution
description: |
    nss-mdns is a plugin for the GNU Name Service Switch (NSS) functionality of
    the GNU C Library (glibc) providing host name resolution via Multicast DNS
    (aka Zeroconf, aka Apple Rendezvous, aka Apple Bonjour), effectively allowing 
    name resolution by common Unix/Linux programs in the ad-hoc mDNS domain .local.
    
    nss-mdns provides client functionality only, which means that you have to
    run a mDNS responder daemon separately from nss-mdns if you want to register
    the local host name via mDNS (e.g. Avahi).
rundeps    :
    - avahi
emul32     : yes
setup      : |
    %configure --enable-avahi \
               --disable-legacy \
               --disable-lynx
build      : |
    %make
install    : |
    %make_install
